const mongoose = require("mongoose");
const { v4: uuidv4 } = require("uuid");

const step5Schema = new mongoose.Schema(
  {
    formId: { type: String, required: true, default: uuidv4 },
    stepId: { type: String, required: true, default: uuidv4 },
    erectile_dysfunction_past: { type: Boolean, default: false },
    erectile_dysfunction_current: { type: Boolean, default: false },
    erectile_dysfunction_interested: { type: Boolean, default: false },
    chronic_pain_past: { type: Boolean, default: false },
    chronic_pain_current: { type: Boolean, default: false },
    chronic_pain_interested: { type: Boolean, default: false },
    physiotherapy_past: { type: Boolean, default: false },
    physiotherapy_current: { type: Boolean, default: false },
    physiotherapy_interested: { type: Boolean, default: false },
    chiropractic_past: { type: Boolean, default: false },
    chiropractic_current: { type: Boolean, default: false },
    chiropractic_interested: { type: Boolean, default: false },
    osteopathy_past: { type: Boolean, default: false },
    osteopathy_current: { type: Boolean, default: false },
    osteopathy_interested: { type: Boolean, default: false },
    massage_past: { type: Boolean, default: false },
    massage_current: { type: Boolean, default: false },
    massage_interested: { type: Boolean, default: false },
    acupuncture_past: { type: Boolean, default: false },
    acupuncture_current: { type: Boolean, default: false },
    acupuncture_interested: { type: Boolean, default: false },
    kinesiology_past: { type: Boolean, default: false },
    kinesiology_current: { type: Boolean, default: false },
    kinesiology_interested: { type: Boolean, default: false },
    podiatry_past: { type: Boolean, default: false },
    podiatry_current: { type: Boolean, default: false },
    podiatry_interested: { type: Boolean, default: false },
    individual_counseling_past: { type: Boolean, default: false },
    individual_counseling_current: { type: Boolean, default: false },
    individual_counseling_interested: { type: Boolean, default: false },
    group_counseling_past: { type: Boolean, default: false },
    group_counseling_current: { type: Boolean, default: false },
    group_counseling_interested: { type: Boolean, default: false },
    couple_counseling_past: { type: Boolean, default: false },
    couple_counseling_current: { type: Boolean, default: false },
    couple_counseling_interested: { type: Boolean, default: false },
    orthotics_past: { type: Boolean, default: false },
    orthotics_current: { type: Boolean, default: false },
    orthotics_interested: { type: Boolean, default: false },
    compression_socks_past: { type: Boolean, default: false },
    compression_socks_current: { type: Boolean, default: false },
    compression_socks_interested: { type: Boolean, default: false },
    tens_unit_past: { type: Boolean, default: false },
    tens_unit_current: { type: Boolean, default: false },
    tens_unit_interested: { type: Boolean, default: false },
    heating_pad_past: { type: Boolean, default: false },
    heating_pad_current: { type: Boolean, default: false },
    heating_pad_interested: { type: Boolean, default: false },
    neck_brace_past: { type: Boolean, default: false },
    neck_brace_current: { type: Boolean, default: false },
    neck_brace_interested: { type: Boolean, default: false },
    back_brace_past: { type: Boolean, default: false },
    back_brace_current: { type: Boolean, default: false },
    back_brace_interested: { type: Boolean, default: false },
    shoulder_brace_past: { type: Boolean, default: false },
    shoulder_brace_current: { type: Boolean, default: false },
    shoulder_brace_interested: { type: Boolean, default: false },
    elbow_brace_past: { type: Boolean, default: false },
    elbow_brace_current: { type: Boolean, default: false },
    elbow_brace_interested: { type: Boolean, default: false },
    wrist_brace_past: { type: Boolean, default: false },
    wrist_brace_current: { type: Boolean, default: false },
    wrist_brace_interested: { type: Boolean, default: false },
    hip_brace_past: { type: Boolean, default: false },
    hip_brace_current: { type: Boolean, default: false },
    hip_brace_interested: { type: Boolean, default: false },
    knee_brace_past: { type: Boolean, default: false },
    knee_brace_current: { type: Boolean, default: false },
    knee_brace_interested: { type: Boolean, default: false },
    ankle_brace_past: { type: Boolean, default: false },
    ankle_brace_current: { type: Boolean, default: false },
    ankle_brace_interested: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Step5", step5Schema);
